### ISSUE TITLE
Host the app in VCL.

### ISSUE THREAD

**Issue by SaikrishnaRajaraman** [SaikrishnaRajaraman/Simplii#12]

**Comment by tripurashree** [comment]
Getting the below error while hosting:

File "application.py", line 71
table_html += f"<tr><td>{user_tasks['taskname']}</td><td>{user_tasks['category']}</td>

**Comment by SaikrishnaRajaraman** [comment]
Schema change issue. Migrated and fixed the issue. Now hosted in VCL.
