### ISSUE TITLE
Schedule reminders once reminder is set for a task

### ISSUE THREAD

**Issue by SaikrishnaRajaraman** [SaikrishnaRajaraman/Simplii#9]

**Comment by SaikrishnaRajaraman** [comment]
Use the flask email scheduler to schedule emails for reminders.

**Comment by tripurashree** [comment]
encountering errors while using flask email scheduler. Need to look into the type conversion of reminder_date parameter.

**Comment by SaikrishnaRajaraman** [comment]
I guess the issue is with ISO date formatting will look into it.
